Change the log level to error so that they show up by default on the console.  Otherwise users may get errors like
error: SyntaxError: Expected "=", "bodyTemplate", "defaults", "headers", "patch", [	], [ ] or [\r\n] but "a" found.

without telling which file is the culprit.